### ISSUE TITLE
这个composer.json的依赖能发给我吗？国内下载不了

### ISSUE THREAD

**Issue by luchanan** [thenbsp/wechat#10]
398778994@qq.com

**Comment by thenbsp** [comment]
Vendor 已发至您的邮箱，另外，作为程序员，类似 “国内下载不了” 的问题应该可以解决，对吧！！！

**Comment by fengqi** [comment]
@luchanan 有很多国内的镜像的, 这个是我测试弄的 https://composer.fengqi.me/
