### ISSUE TITLE
求问怎么整合到laravel5中,谢谢

### ISSUE THREAD

**Issue by ancon** [thenbsp/wechat#11]
如题

**Comment by thenbsp** [comment]
Laravel 支持 Composer，直接安装就可以使用，如果想更优雅的方式，可以将 SDK 定义为服务，详情请参考 [Service Container](https://laravel.com/docs/5.2/container) 章节！

**Comment by ancon** [comment]
laravel确实支持composer,不过,用composer安装不上,与系统本身的required冲突

**Comment by thenbsp** [comment]
与系统本身的 required 冲突？？？那你安装别的 package 是怎么安装的？

**Comment by liang-h** [comment]
这次版本变化有点太大了。还好之前的文档我有重新备份了一封。不家一个问题，对于初始化时。AppId等这些参数可否一次设置就OK

**Comment by ancon** [comment]
其他的话,因为是之前加载好的依赖,安装这个库的时候,与之前的依赖冲突,这样进行不下去,又回滚了...

**Comment by thenbsp** [comment]
事实上，大部分接口都只依赖全局 AccessToken，只有一小部分比如 OAuth, Payment 等不可避免的需要传入 appid
等参数，通常来说，这个 SDK 在框架里使用的时间，经常会定义为 Service，比如我使用最多的 Symfony，或者其它支持 服务容器
的框架，定义成 Service 之后，可以根据服务 ID 全局调用，不存在你说的每次都需要设置 appid 等参数！

另外，本次刚刚发布了 2.x 版本，与之前的版本改变较大（所以不再是 1.x，而是直接跳到 2.x），所支持的 PHP 版本也升级为
5.5.9，你与之前的依赖冲突，具体是因为哪个 package 呢？

在 2016年3月26日 上午1:55，钟宇 <notifications@github.com>写道：

**Comment by ancon** [comment]
@thenbsp 谢谢您的耐心回答.有图有真相吧:
![wechat](https://cloud.githubusercontent.com/assets/6762451/14060193/0abc7542-f397-11e5-85a6-b830473acd63.PNG)

**Comment by thenbsp** [comment]
这个问题原因在于你的 laravel 框架使用了 Symfony/Http-founcdation 2.7.10 的版本，而 SDK 本身使用了
3.0.1 的版本，因此会出现不兼容，要解决这个问题有两种方案：

1，升级你的 Laravel 到 5.2
2，降级 thenbsp/wechat 到 1.1.7

如果你选择降级，那么之前写好的代码可以需要改动！

2016-03-26 21:09 GMT+08:00 钟宇 <notifications@github.com>:

**Comment by ancon** [comment]
good,您说的2种方案都可解决~
如果使用1.1.7版本,会不会有什么问题呢?

**Comment by thenbsp** [comment]
不会有什么问题的，放心用吧！

2016-03-28 11:11 GMT+08:00 钟宇 <notifications@github.com>:

**Comment by ancon** [comment]
给力,太棒了!
