### ISSUE TITLE
共享地址的国家三级问题

### ISSUE THREAD

**Issue by ancon** [thenbsp/wechat#12]
建议加上国家三级区域 = addressCountiesThirdStageName
微信的命名规则很niubility

**Comment by ancon** [comment]
<script>
var getAddress = function() {
    if( typeof WeixinJSBridge === 'undefined' ) {
        alert('请在微信在打开页面！');
        return false;
    }
    WeixinJSBridge.invoke('editAddress', <?php echo $config; ?>, function(res) {
        switch(res.err_msg) {
            case 'edit_address:ok':
                document.getElementById('name').innerHTML = res.userName;
                document.getElementById('mobile').innerHTML = res.telNumber;
                document.getElementById('provice').innerHTML = res.proviceFirstStageName;
                document.getElementById('city').innerHTML = res.addressCitySecondStageName;

                # **_document.getElementById('district').innerHTML = res.addressCountiesThirdStageName;_**

                document.getElementById('address').innerHTML = res.addressDetailInfo;
                document.getElementById('postalCode').innerHTML = res.addressPostalCode;
                document.getElementById('nationalCode').innerHTML = res.nationalCode;
                break;
            case 'edit_address:fail':
                alert('获取编辑收货地址失败！');
                break;
            case 'edit_address:cancel':
                alert('您已取消获取地址！');
                break;
            default:
                alert(JSON.stringify(res));
                break;
        }
    });
}
</script>

**Comment by thenbsp** [comment]
JS 默认返回是带 addressCountiesThirdStageName 的，跟后台生成配置没关系，你可以直接使用  res.addressCountiesThirdStageName 来获取结果，只是我示例中没写罢了。
