### ISSUE TITLE
WIKI文档是针对2.0版本，而release是1.1.7

### ISSUE THREAD

**Issue by HanSon** [thenbsp/wechat#13]
导致无法开发，希望尽快上传1.1.7的文档

**Comment by thenbsp** [comment]
你好，2.0 之前的版本文档都是在源码包里，你可以直接 tags  里面找到，同时还有相应代码示例 (example) 目示：

https://github.com/thenbsp/wechat/tree/v1.1.7

2016-08-11 12:16 GMT+08:00 HanSon <notifications@github.com>:

**Comment by HanSon** [comment]
好吧，暂时也只能这样的了，谢谢了
