### ISSUE TITLE
$client->getAccessToken($code); 获取不到

### ISSUE THREAD

**Issue by AndroidKid19** [thenbsp/wechat#14]
这是我的代码，麻烦大神给处理一下 thinkyou 
<?php
require 'ThinkPHP/Library/Vendor/autoload.php';
use Thenbsp\Wechat\OAuth\Client;
header("content-type:text/html;chartset=utf-8");
if (isset($_GET['code'])) {
    $code = $_GET["code"];
} else {
    echo "NO CODE";
}
$client = new Client('wx6eb5967405d60a95', 'c53a74ee3155f86d3c0f47f9e50ded2d');

var_dump($code);
$accessToken = $client->getAccessToken($code);
var_dump($accessToken);

**Comment by thenbsp** [comment]
请参考网页授权，这是基本的 OAuth2 认证，你这姿势不对！

https://github.com/thenbsp/wechat/wiki/oauth_client

**Comment by AndroidKid19** [comment]
大神为啥你不提供个示例呢！

**Comment by AndroidKid19** [comment]
@thenbsp  大神你为啥不提供个demo示例呢！

**Comment by AndroidKid19** [comment]
@thenbsp @thenbsp  require THINK_PATH . 'Library/Vendor/autoload.php';
use Thenbsp\Wechat\OAuth\Client;
class IndexController extends BaseController
{
    public $client;
    public function index()
    {
        // $redirect_uri = 'http://www.soft-cloud.cc/SourceCode/YuanWeiWei/FunButton/index.php/?m=Home&c=Text&a=getAccessToken2';
        $redirect_uri = 'http://www.soft-cloud.cc/SourceCode/YuanWeiWei/FunButton/oauth2.php';
        $this->client = new Client('wx6eb5967405d60a93', 'c53a74ee3155f86d3c0f47f9e50ded23');
        // dump($_GET['code']);
        if (! isset($_GET['code'])) {
            $this->client->setRedirectUri($redirect_uri);
            $this->client->setScope("snsapi_userinfo");
            $this->client->setState("1");
            $this->logResult('/getAuthorizeUrl.log', $this->client->getAuthorizeUrl());
            header('Location: ' . $this->client->getAuthorizeUrl());
        }
        $accessToken = $this->client->getAccessToken($_GET["code"]);
        // $userinfo = $accessToken->getUser();
        // dump($userinfo->toArray());
    }

**Comment by thenbsp** [comment]
@AndroidKid19 示例：

```
use Thenbsp\Wechat\OAuth\Client;

$client = new Client('appid', 'appsecret');

if( !isset($_GET['code']) ) {
    header('Location: '.$client->getAuthorizeUrl());
}

$accessToken = $client->getAccessToken($_GET['code']);

var_dump($accessToken->toArray());
```

**Comment by xuwu125** [comment]
@thenbsp 
你这个示例，我测试结果是一直显示 RedirectUri错误

**Comment by thenbsp** [comment]
RedirectUri 错误？你确定你在公众后台配置了正确的 redirect_url 吗？
