### ISSUE TITLE
找不到ArrayCollection

### ISSUE THREAD

**Issue by huguozhi** [thenbsp/wechat#15]
Fatal error: Class 'Doctrine\Common\Collections\ArrayCollection' not found

请问，这是需要第三方库吗？

**Comment by thenbsp** [comment]
你使用 composer install 安装了没？

2016-10-06 11:41 GMT+08:00 huguozhi <notifications@github.com>:

**Comment by huguozhi** [comment]
没有，我直接下载的，我想整合到codeigniter里，请问能给点建议吗？有别的联系方式吗？

发自我的 iPhone

**Comment by thenbsp** [comment]
你这使用姿势不对，Composer Packages 都需要安装依赖的，直接下载肯定不能用啊！

**Comment by huguozhi** [comment]
谢谢，我试试

发自我的 iPhone
