### ISSUE TITLE
无法使用composer安装

### ISSUE THREAD

**Issue by Mashil** [thenbsp/wechat#16]
请问现在composer安装是不是有问题，没办法下载下来

**Comment by thenbsp** [comment]
Composer 安装没有问题，如果下载失败，可能是你那边网络问题吧，多试几次，如果还是没行，联系我给你发整个 vendor！

**Comment by yoage** [comment]
composer 安装是没有问题的，我的项目在用

**Comment by tindynnic** [comment]
求楼主完整vendor！本人被composer折腾疯了，各种报错少了文件，本人邮箱：1602688591@qq.com，非常非常感谢了！

**Comment by thenbsp** [comment]
你的环境版本和我的不一定一样，不过我发给你了，你试一下。

2017-03-27 14:56 GMT+08:00 tindynnic <notifications@github.com>:

**Comment by xuwu125** [comment]
使用 composer 中国镜像 就好了。
