### ISSUE TITLE
请教关于这个源码的几个问题

### ISSUE THREAD

**Issue by hrbwaxdoll** [thenbsp/wechat#18]
看了一下，基本上是接口的封装，那大神有没有一个Demo可以让我这种小白可以理解这个SDK的使用方法呢？

我是用在Yii2这个框架中，感觉您的代码还是挺易读的，但是无从下手。

**Comment by hrbwaxdoll** [comment]
哦，其实还有几个问题，但是如果能有一个基础，其它几个问题应 该 都不是问题了。

**Comment by thenbsp** [comment]
2.0 之前的版本都有 demo 示例，比如 1.1.7 https://github.com/thenbsp/wechat/tree/v1.1.7/example，另外 2.0 接口有化变，所以 example 仅供参考！
