### ISSUE TITLE
使用二维码扫码登录时，报错 Invalid Authentication State "xxxxxxxxx"

### ISSUE THREAD

**Issue by lfire** [thenbsp/wechat#24]
[0] Exception in AbstractClient.php line 113
Invalid Authentication State "NxVaLjsuw62Pl0dX"
    public function getAccessToken($code, $state = null)
    {
        if (null === $state && !isset($_GET['state'])) {
            throw new \Exception('Invalid Request');
        }

        // http://www.twobotechnologies.com/blog/2014/02/importance-of-state-in-oauth2.html
        $state = $state ?: $_GET['state'];
        if (!$this->stateManager->isValid($state)) {
            throw new \Exception(sprintf('Invalid Authentication State "%s"', $state));
        }

        $query = array(
            'appid'         => $this->appid,
            'secret'        => $this->appsecret,
            'code'          => $code,
            'grant_type'    => 'authorization_code'
        );

**Comment by thenbsp** [comment]
这个异常是由于授权跳前的 state 和之后的 state 值不一致造成的，你可以指定第二个参数来手动指定 state 参数：

```
$client->getAccessToken($code, $_GET['state']);
```
