### ISSUE TITLE
微信支付通知，验证参数需要自己弄

### ISSUE THREAD

**Issue by GDUTKiller** [thenbsp/wechat#29]
项目开发到现在，才发现你写的微信支付通知，需要自己去签名认证

**Comment by GDUTKiller** [comment]
我写了个签名认证 
        $check = [];
        foreach ($notify as $k => $v) {
            if ($k != 'sign') {
                $check[$k] = $v;
            }
        }

        ksort($check);
        $str = http_build_query($check);
        $str = $str  . '&key=' . config('constants.wx_mch_key');
        $sign = strtoupper(md5($str));
        if ($sign != $notify['sign']) {
            //签名不正确
        }

**Comment by thenbsp** [comment]
支付通知默认只验证了数据结构，没有验证签名。
