### ISSUE TITLE
为什么会有Symfony。。。

### ISSUE THREAD

**Issue by shaukei** [thenbsp/wechat#3]
https://github.com/thenbsp/wechat/blob/master/src/Util/OptionValidator.php

为什么要有Symfony

赶紧自己实现一个，跟Symfony去藕啊！！！！！！！！！！！

**Comment by thenbsp** [comment]
OptionsResolver 用来合并和校验参数的，也是本着不重复造轮子的原则，另个，还依赖 guzzlehttp/guzzle，请参考 /composer.json

**Comment by yellowbig** [comment]
这种用法挺常见的吧，用sf2的某个component而已，laravel，drupal8，phpbb...很多都是这么用，也不会像sylius那几个full stack的那么重，没什么必要解吧

**Comment by thenbsp** [comment]
@yellowbig 正解
