### ISSUE TITLE
引用后显示找不到class类文件件

### ISSUE THREAD

**Issue by SummerMagic** [thenbsp/wechat#30]
Uncaught exception 'Shopnc\Exception'
with message 'Class Error: cannot autoload 
class: Thenbsp\Wechat\OAuth\Client

命名空间 
use Shopnc\Tpl;
use Thenbsp\Wechat\OAuth\Client;

$client = new Client($this->appid , $this->secret);
		if( !isset($_GET['code']) ) {
			header('Location: '.$client->getAuthorizeUrl());
		}
	echo 1111;die;

**Comment by thenbsp** [comment]
看起来你的错误是由 ``Shopnc\Exception`` 这个类没有找到引起的，和 SDK 无关。
