### ISSUE TITLE
你好，请教，微信扫码登录是否能用于三级域名

### ISSUE THREAD

**Issue by zhaohng** [thenbsp/wechat#31]
你好，请教，微信开发平台，网站扫码登录，授权回调域为二级域名 xxx.com，请问该应用是否支持 xxx.xxx.com 三级域名。如果支持，对于不同的三级域名，比如a.xxx.com和b.xxx.com 同一用户返回的access_token是否相同。如果不支持，修改授权回调域后，修改前后，同一用户返回的access_token是否相同。

**Comment by thenbsp** [comment]
扫码登录需要在 **微信开放平台** （不是公众号后台）配置授权域名，可以使用三级域名。
