### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'api unauthorized, hints: [ req_id: dIaOLa0186s154 ]' in /www/wx/vendor/thenbsp/wechat/src/OAuth/AccessToken.php:68 Stack trace: #0

### ISSUE THREAD

**Issue by senmeng** [thenbsp/wechat#32]
Fatal error: Uncaught exception 'Exception' with message 'api unauthorized, hints: [ req_id: dIaOLa0186s154 ]' in /www/wx/vendor/thenbsp/wechat/src/OAuth/AccessToken.php:68 Stack trace: #0

**Comment by thenbsp** [comment]
很显然你没有此接口调用权限，请确认公众号已获得该接口，可以在公众平台官网-开发者中心页中查看接口权限
