### ISSUE TITLE
您好，我获取access_token一直提示ip不在白名单，怎么处理

### ISSUE THREAD

**Issue by zhaoyunxing92** [thenbsp/wechat#33]
我开发阶段提示ip不在白名单的话我可以去微信公众平台后台添加，但是上线了怎么处理啊，不可能每个人的ip都添加吧

**Comment by wmet** [comment]
使用VPN鏈接，相當於有了一個固定IP

**Comment by zhaoyunxing92** [comment]
是线上啊IP不可能固定的

**Comment by thenbsp** [comment]
获取 AccessToken 参照 https://github.com/thenbsp/wechat/wiki/wechat_access_token
