### ISSUE TITLE
在thinkphp框架中怎么监听关注事件啊？

### ISSUE THREAD

**Issue by wanrende** [thenbsp/wechat#34]
在thinkphp框架中怎么监听关注事件啊？我试了一下午没结果。

**Comment by ety001** [comment]
表示如何获取event中的数据？

**Comment by thenbsp** [comment]
消息回调中的 Event 事件就是消息数据，这是一个 ArrayAccess 类型，具体参考 https://github.com/thenbsp/wechat/wiki/event_response

**Comment by ety001** [comment]
比如说用户发了一条消息是『hi』，我如果从event中拿到这个『hi』，用$event->getContent()？

对于ArrayCollection并不熟悉。看了 doctrine 的 ArrayCollection，并没有找到一个可以用的方法，拿到这个 『hi』。

**Comment by thenbsp** [comment]
用户发布文字消息的 XMl 体类似以下结构：

```
<xml>
    <ToUserName><![CDATA[gh_08cb40357652]]></ToUserName>
    <FromUserName><![CDATA[ob4npwpYsDT6CQGHRDl9U50V6-RE]]></FromUserName>
    <CreateTime>1461938829</CreateTime>
    <MsgType><![CDATA[text]]></MsgType>
    <Content><![CDATA[文字消息]]></Content>
    <MsgId>6278979459712291404</MsgId>
</xml>
```

``Event`` 是一个 ArrryAccess 类型，因此直接使用：

```
$event['ToUserName'] // 接收者名称
$event['FromUserName'] // 发送者名称
$event['Content'] // 文字内容
// ...
```

具体请参考官方文档：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140453
