### ISSUE TITLE
使用最新的代码，composer报错

### ISSUE THREAD

**Issue by bing15** [thenbsp/wechat#36]
Using version dev-master for thenbsp/wechat
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package thenbsp/wechat No version set (parsed as 1.0.0) is s
atisfiable by thenbsp/wechat[No version set (parsed as 1.0.0)] but these conflic
t with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by thenbsp** [comment]
从错误来看应该是你使用了 ``dev-master`` 分支造成的，请检查 ``composer.json`` 中的 ``minimum-stability`` 参数为 ``stable`` 或 默认（不填）


```
// composer.json

{
    // ...
    "thenbsp/wechat": "^2.0,
    "minimum-stability": "stable"
    // ...
}
```

然后执行 ``composer update``
