### ISSUE TITLE
期待WIKI发布

### ISSUE THREAD

**Issue by shrekmaxi** [thenbsp/wechat#4]
对于我这样的菜鸟来说，实在是不会用....

**Comment by thenbsp** [comment]
/documentation 目录面就是文档，另外 /example 下有每一个功能的详细示例，你可以通过 composer require thenbsp/wechat 安装，设置好公众号 appid/appsecret 之后，在你的本地运行测试每一个功能。

**Comment by shrekmaxi** [comment]
再弱弱地问一句:appid/appsecret在哪里设置？ 另外我用composer安装之后生成的vendor目录下的内容是都需要么？

**Comment by thenbsp** [comment]
Wechat 对象就是用来管理 appid/appsecret 的，设置好之后，所以需要的地方只需注入 Wechat 对象就可以，不需要关心 appid/appsecret 这些细节，可以参考:

https://github.com/thenbsp/wechat/blob/master/documentation/wechat.md

另外，示例中有详细的示例：

https://github.com/thenbsp/wechat/blob/master/example/example.php

**Comment by shrekmaxi** [comment]
多谢。那么我编辑example.php文件里面的相关内容就是设置appid/appsecret了是吧？

**Comment by thenbsp** [comment]
你可以直接在 /example/example.php 设置 appid/appsecret 这后就可以运行。

**Comment by shrekmaxi** [comment]
thanks a lot. you are being so kind
