### ISSUE TITLE
签名生成器类是否已经彻底remove，未来也不再考虑添加？

### ISSUE THREAD

**Issue by yellowbig** [thenbsp/wechat#7]
看到目前最新的版本中Util/SignGenerator工具类已经没有了，想问下 @thenbsp 这块是否在未来的版本中也不会再加入回来了呢？

**Comment by thenbsp** [comment]
是的， SignGenerator 已被移除，未来不会再加入进来，你如果需要，可以在历史版本中找到！

https://github.com/thenbsp/wechat/blob/v1.0.0/Util/SignGenerator.php

**Comment by yellowbig** [comment]
了解了，多谢！
