### ISSUE TITLE
关注动作失效

### ISSUE THREAD

**Issue by shaukei** [thenbsp/wechat#8]
关注时，服务器返回的数据：
<xml><ToUserName><![CDATA[xxx]]></ToUserName>
<FromUserName><![CDATA[xxxx]]></FromUserName>
<CreateTime>1447921517</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[subscribe]]></Event>
<EventKey><![CDATA[]]></EventKey>

相关代码：
case ($this->_option['Event'] === 'subscribe') :
                return array_key_exists('EventKey', $this->_option) ?
                    Event::EVENT_QRCODE_UNSUBSCRIBE : Event::EVENT_SUBSCRIBE;
                break;

这里的逻辑，是返回了Event::EVENT_QRCODE_UNSUBSCRIBE。
是不是微信的数据变了，你没有及时更新呢？

**Comment by shaukei** [comment]
关注时候，微信服务器传EventKey是空值,所以，，
call_user_func_array($event, array(new Thenbsp\Wechat\Message\Event\EventSubscribe($this->_option)));
这里 new EventSubscribe 是不能成功的。
The option "EventKey" does not exist. Defined options are: "CreateTime", "Event", "FromUserName", "MsgType", "ToUserName".

**Comment by thenbsp** [comment]
根据相关文档，关注/取消关注事件没有 EventKey，扫码关注/未关注时才会有。

http://mp.weixin.qq.com/wiki/14/f79bdec63116f376113937e173652ba2.html#.E5.85.B3.E6.B3.A8.2F.E5.8F.96.E6.B6.88.E5.85.B3.E6.B3.A8.E4.BA.8B.E4.BB.B6

**Comment by thenbsp** [comment]
问题已修复，请更新：

```
composer update thenbsp/wechat
```
